### ISSUE TITLE
need TLS support

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/dropshot#10]
It would be great if Dropshot provided an ergonomic way for consumers to put their server behind TLS.  What this means is a little up in the air, but I imagine we'd need to do some combination of:

- pick a library for doing TLS and integrate it with `HttpServer`
- provide configuration for specifying that you want TLS
- provide configuration for specifying a certificate (for custom certs) and any other security-related params
- ideally: provide an easy way to use letsencrypt or something like that, particularly for development

It's worth a bit of research to see what libraries and best practices are out there already for doing this in Rust.

**Comment by steveklabnik** [comment]
https://crates.io/crates/native-tls is a good default, IMHO. https://crates.io/crates/rustls was recently audited and the auditors were impressed.

**Comment by rmustacc** [comment]
A related question is what types of TLS do we need to support? For example, rustls seems not to support TLS v1.1 or v1.0, which is reasonable. It'd be nice to only get away with supporting TLS v1.2+.

**Comment by davepacheco** [comment]
Link to the audit report for rustls, for reference: https://github.com/ctz/rustls/blob/master/audit/TLS-01-report.pdf

**Comment by Spoonbender** [comment]
@rmustacc TLS 1.0 and 1.1 were [formally deprecated](https://datatracker.ietf.org/doc/rfc8996/) so it seems getting away with it is easier than ever nowadays

**Comment by johnhurt** [comment]
Even if rustls isn't the final solution, the [hyper-rustlts](https://crates.io/crates/hyper-rustls) crate makes it easy to evaluate. It's almost  a drop-in solution

https://github.com/ctz/hyper-rustls/blob/master/examples/server.rs

**Comment by steveklabnik** [comment]
More momentum for rustls: https://www.abetterinternet.org/post/preparing-rustls-for-wider-adoption/

**Comment by kulakowski** [comment]
I'm probably gonna pick this up in a sec as my first project, per the last CP tactical, cc @smklein

**Comment by ahl** [comment]
Thank you @kulakowski!

**Comment by kulakowski** [comment]
https://rfd.shared.oxide.computer/rfd/0010 4.5

First, a quick evaluation of some relevant crates. tl;dr rustls has momentum, is ready for primetime, and is a good direction to pick.


I'm assuming we're not in the business of rolling our own on top of ring/boringssl/ and a cert management crate or anything like that. I'm also assuming from a quick grep that tokio and hyper integration is desirable.

I'm also assuming that rustls, or ring which backs it, don't have a feature gap. https://docs.rs/rustls/0.19.1/rustls/#non-features lists non-features. If there's a business reason we need to expose TLS1.1 to someone, I don't think it'd be terribly expensive to redo this work with eg native-tls or boring.


### https://crates.io/crates/rustls
Backed by ring for cryptography and libwebpki for certificate management. There are some sibling crates for things like cert management and hyper utilities and so on.

Somewhat recently announced interface stability, and traction and adoption from projects like apache httpd and curl, besides the rust ecosystem itself.

rustls was security audited, as mentioned above, to basically a rave review.

The exposed APIs are slightly higher level than some other crates which basically pass through openssl/boringssl. Getting a read_tls and write_tls set of methods and avoid the subtle boilerplate is reason enough for me to want to pick this one.


### https://crates.io/crates/native-tls
A wrapper around a platform specific tls solution, which for illumos would mean openssl.so. On macos it's a wrapper around security.framework or however it's spelled. Some other crates in the ecosystem provide eg hyper integration.


In less detail:

### https://crates.io/crates/hyper-tls
An https connector for hyper, backed by native-tls.

### https://crates.io/crates/openssl
A wrapper around openssl.so.

### https://crates.io/crates/boring
Cloudflare's wrapper around boringssl, along with plugins into the tokio and hyper ecosystems.

### https://crates.io/crates/mundane
Fuchsia's wrapper around a vendored copy of boringssl. I see little reason to prefer it over something ring-based, or over Cloudflare's boring which is better integrated into tokio etc.

**Comment by davepacheco** [comment]
I think this was resolved some time ago.
