### ISSUE TITLE
Documentation on crates.io

### ISSUE THREAD

**Issue by yerke** [oxidecomputer/dropshot#111]
I just stumbled on dropshot and when I went to [crates.io](https://crates.io/crates/dropshot) to check it out, it said `dropshot v0.5.1 appears to have no README.md file`.

I see that docs.rs has the dropshot docs.

Will it be possible to investigate what is wrong with crates.io?

**Comment by davepacheco** [comment]
I believe the problem is that crates.io does not look at Asciidoc READMEs. I looked into this at one point and it seemed to be a desired feature for crates.io but probably not a high priority for them.

**Comment by yerke** [comment]
Would it make sense to add a small markdown README that would contain a link to docs.rs maybe?
