### ISSUE TITLE
Serve static files

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/dropshot#115]
Web frameworks tend to make it easy to serve a local directory of static assets from an arbitrary route prefix. If we don't want to build something one-liner-ish into Dropshot directly, it would still be helpful to have an example somewhere of how to do it by hand.

This could be done dynamically with a wildcard route (#110) or use the directory listing of the asset directory to generate a static list of routes at compile time, which makes the wildcard route unnecessary. It's hard to tell, but I think Rocket is [doing the former](https://github.com/SergioBenitez/Rocket/blob/a26f93c57298612fd83e2c37edd0a6bbd7d18fdf/core/lib/src/fs/server.rs#L184) and Actix is doing the latter.

### Rocket ([example](https://github.com/SergioBenitez/Rocket/blob/f1ecb79a7ea536bacc7b7e92d33bf5406c0c635f/examples/static-files/src/main.rs))

```rs
use rocket::fs::{FileServer, relative};

#[rocket::launch]
        fn rocket() -> _ {
            rocket::build()
                .mount("/", FileServer::from(relative!("static")))
        }
```

### Actix ([docs](https://actix.rs/docs/static-files/))

```rs
use actix_files as fs;
use actix_web::{App, HttpServer};

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new().service(fs::Files::new("/static", ".").show_files_listing())
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}
```

### Express ([docs](https://expressjs.com/en/starter/static-files.html))

```js
app.use('/static', express.static('public'))
```

**Comment by ahl** [comment]
@david-crespo I could imagine a slightly beefed up example from what I'm adding in #110 that looks at the filesystem and responds with either a file or error, setting the content type based on file extension (I guess?). Would that suffice?

**Comment by david-crespo** [comment]
Yep. Some prior art:

https://github.com/SergioBenitez/Rocket/blob/a26f93c5/core/lib/src/fs/server.rs#L212
https://github.com/SergioBenitez/Rocket/blob/a26f93c5/core/lib/src/fs/named_file.rs#L66
https://github.com/SergioBenitez/Rocket/blob/a26f93c5/core/lib/src/fs/named_file.rs#L152
https://github.com/SergioBenitez/Rocket/blob/a26f93c5/core/http/src/header/content_type.rs#L99-L101
https://github.com/SergioBenitez/Rocket/blob/a26f93c5/core/http/src/header/known_media_types.rs
