### ISSUE TITLE
add tags to paths

### ISSUE THREAD

**Issue by jessfraz** [oxidecomputer/dropshot#127]
most other api clients use tags to denote what category the path is in. Its fairly consistent so I have been using them to determine what "file/module" to put the function in. Now I am getting this for the meantime from the path, but as this is an inconsistency with other generated specs from other apis we might want to fix it.

**Comment by ahl** [comment]
Dropshot does support tags:

https://docs.rs/dropshot/0.5.1/dropshot/attr.endpoint.html

Are you asking that we use tags in the omicron endpoints or that we derive them from the path in Dropshot? The former makes sense to me; the latter seems more opinionated, but it's meant to be an opinionated framework so seems worth considering.

**Comment by jessfraz** [comment]
Doesnt matter, but just saying whatever you do that becomes the
modules https://docs.rs/octorust/0.1.26/octorust/#modules

**Comment by ahl** [comment]
the `tags` field can accommodate multiple tags e.g. https://github.com/slackapi/slack-api-specs/blob/master/web-api/slack_web_openapi_v2_without_examples.json

Is your generator going to use the first tag you see?

In any case, let's open a bug against the actual API where we want tags and specify how we want to use them.

**Comment by jessfraz** [comment]
Yup it takes the first! Tbh no other api has more than one but I switched it for you all when I realized that wasn’t a constraint
