### ISSUE TITLE
weird request: parsing url fragment like query string

### ISSUE THREAD

**Issue by jessfraz** [oxidecomputer/dropshot#131]
there is a weird API that uses the URL fragment (https://developer.shipbob.com/auth) versus the query string for the requests. Is it easy to make query params work with the fragment as well? like if I wanted to PR it otherwise just gunna continue doing the gross shit I do to get the original request then parse it, like for encoded forms and crap

**Comment by davepacheco** [comment]
I wonder if this is valid HTTP.  [Browsers don't send the fragment to the server](https://stackoverflow.com/questions/940905/can-i-read-the-hash-portion-of-the-url-on-my-server-side-application-php-ruby) and [Wikipedia says](https://en.wikipedia.org/wiki/URI_fragment):

> Clients are not supposed to send URI fragments to servers when they retrieve a document

Might there be security implications (or other issues) from trying to interpret this?

**Comment by jessfraz** [comment]
I found a way to change it to a post form encoded so all good now, but yeah I mean params are the exact same thing you can see it in the URL so any security implications would be the same for fragments
