### ISSUE TITLE
generate openapi summary

### ISSUE THREAD

**Issue by jessfraz** [oxidecomputer/dropshot#244]
this will be the first line of the doc comment with the longer description being the rest if it is longer

**Comment by jessfraz** [comment]
related to https://github.com/oxidecomputer/omicron/issues/535

**Comment by ahl** [comment]
Rustdoc uses the first line as a summary:

```
/// This is the summary!
///
/// Here are some more details!
```

![image](https://user-images.githubusercontent.com/677483/149807295-53a2e7d4-e18f-46fd-a24b-df49c9f8ecfe.png)

![image](https://user-images.githubusercontent.com/677483/149807408-f2afefb1-c6d2-450d-b467-eb39de1db1d5.png)

I'd suggest we
1. use the first line as the summary
2. use the rest as the description
3. add a lint to make sure the summary is sufficiently pithy (@jessfraz can you suggest a maximum number of characters?)

Alternatively, we could do something like this:

```rust
#[endpoint {
    method = GET,
    path = "/foo",
    summary = "get foos"
}]
/// The foo getter must take a valid foo ID which is derived from the....
async fn blah_blah_blah(
```

I like that the OpenAPI docs come from the rust docs, but I consent that that's a matter of opinion.

**Comment by jessfraz** [comment]
yeah i like the first line thing

Basically something like "Get instance" "List all instances", "Update an instance", I would say chars around a 12-20 give or take. Maybe max 20

**Comment by jessfraz** [comment]
fwiw the first line rust doc comment is how clap works with parsing cli usage/docs as well
