### ISSUE TITLE
ergonomic issue with anyhow Error usage

### ISSUE THREAD

**Issue by jclulow** [oxidecomputer/dropshot#37]
Not completely clear what to do here, but I wanted to highlight something about the API as it works today that presents at least a slight rough edge.

When failing, it seems a handler is expected to produce a `HttpError` of some sort (e.g., for a 500-style server failure, or a 400-style client failure).  Often, at least while getting started with a new program, it is convenient to use the `anyhow::Error` object: a basic string-based error with the ability to hold a cause chain and attach context.

Unfortunately, because of the Rust rules around Trait implementation it is not possible to implement `From` or `Into` to convert directly from `anyhow::Error` to an appropriate `HttpError` for the application; neither type is in my crate, and thus extension is prohibited.  This means you cannot trivially use the `?` operator.  I worked around this using a pattern similar to the `anyhow::Context` trait `context()` method, providing my own extension trait:

```rust
trait AnyhowHttpError<T> {
    fn or_500(self) -> std::result::Result<T, HttpError>;
    fn or_400(self) -> std::result::Result<T, HttpError>;
}

impl<T> AnyhowHttpError<T> for anyhow::Result<T> {
    fn or_500(self) -> std::result::Result<T, HttpError> {
        self.map_err(|e| {
            let msg = format!("internal error: {}", e);
            HttpError::for_internal_error(msg)
        })
    }

    fn or_400(self) -> std::result::Result<T, HttpError> {
        self.map_err(|e| {
            HttpError::for_client_error(None, hyper::StatusCode::BAD_REQUEST,
                format!("request error: {}", e))
        })
    }
}

#[endpoint {
    method = GET,
    path = "/some/endpoint",
}]
async fn handle_fetch(
    rqctx: Arc<RequestContext>,
) -> std::result::Result<HttpResponseOk<SomeResult>, HttpError> {
    let c = Context::from_request(&rqctx);

    /*
     * generate_response() returns anyhow::Result<SomeResult>:
     */
    Ok(HttpResponseOk(c.generate_response().or_500()?))
}
```

**Comment by davepacheco** [comment]
Thanks for filing this.  Seeing the specifics helps a lot.  I think there are two slightly different issues here.

First, even if you could somehow define a translation from `anyhow::Error` to `HttpError`, it looks to me like it would require context that's not part of the `anyhow::Error`.  In particular, the call site looks like it's deciding whether to produce a 400 or 500 status code.  This has been my experience as well: the status code usually depends on call site context that's not present in the error itself.  For example, I used to define a translation from `serde_json::Error` to `HttpError` that would produce a 400 ("Bad Request") response, assuming that such an error was a problem with the request body.  Not surprisingly, I ran into cases where failure to parse JSON was a server error, not a client error.  (In my case, this was parsing the server-generated pagination token, but you can easily imagine this happening when parsing a database record that was fetched as part of the request.)  As a consequence, I've changed to mostly using `map_err()` as you have done here.  As long as the call site needs to provide some information about what kind of `HttpError` to produce, I'm not sure there's a more ergonomic way than to use `map_err()`.

In the more complex use case where we're using Dropshot ("oxide-api-prototype"), we have an HTTP-agnostic error enum with a lot of different variants.  There's a clear translation from this type to `HttpError` based on which variant it is.  But that doesn't really change the problem: it just pushes it around.  We still have the problem of determining which variant to create based on a type like `serde_json::Error`, and that generally still uses `map_err()`.

That said, maybe it would be nice if you could define such translations for cases where you do know that a certain error type necessarily always results in a particular kind of `HttpError`.  I'm not sure how best to solve this, but given the above, I'm not sure how much it will come up in practice.  I haven't come up with an example.

Thoughts?

**Comment by jclulow** [comment]
I pretty much agree completely with your assessment.  Though I think we could provide something in the base library that's a little like what I have above, with chainable options that can hang off a `Result` with any displayable `Error` type, I suspect in practice the benefit would be relatively slight.  I expect it would require either a lot of knobs (and thus be less ergonomic than just using `map_err()` as you say) or be inflexible and thus not terribly useful once people advance the maturity of their consumer.

Perhaps this is more of a documentation or example usage pattern sort of thing, at least until we see more how this ends up being used?

**Comment by davepacheco** [comment]
That sounds good.

Note that today, I think you'd do:

```rust
your_error.map_err(|e| HttpError::for_bad_request(None, e.to_string()))
/* or */
your_error.map_err(|e| HttpError::for_internal_error(None, e.to_string()))
```

The `None` is kind of a wart because of the way error codes work -- I will file a separate bug on that.  If we manage to get rid of that, then maybe we could parametrize these functions so that they work on `T: ToString` (is that the right trait here? that would be anything that implements `Display`).  Then you could do:

```rust
your_error.map_err(HttpError::for_bad_request)
/* or */
your_error.map_err(HttpError::for_internal_error)
```

**Comment by davepacheco** [comment]
Reading back, I think this is no longer actionable, but feel free to reopen if that's wrong.
