### ISSUE TITLE
exemple to use swagger-ui

### ISSUE THREAD

**Issue by doubleailes** [oxidecomputer/dropshot#566]
Hello,

Anyone have a exemple to exemple a `swagger-ui` like interface?

Thanks.

**Comment by david-crespo** [comment]
My understanding is that Swagger UI is mostly independent of Dropshot. The point of contact between the two is the OpenAPI spec. You generate an OpenAPI spec from your Dropshot server using [`write`](https://docs.rs/dropshot/latest/dropshot/struct.OpenApiDefinition.html#method.write) (example [here](https://github.com/oxidecomputer/dropshot/blob/5f27e8da5b9ff03a835df7648e00a97d67a1ddd3/dropshot/examples/schema-with-example.rs#L51-L60)). Then you plug that spec into swagger-ui using the `spec` or `url` field in the swagger-ui configuration ([docs](https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/configuration.md)).
