### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by mikeyhew** [oxidecomputer/dropshot#59]
Hey there! I was playing around with Dropshot, and noticed there isn't anything in the documentation yet about auth/security. Do you have any recommendations on how to do auth with Dropshot, or have any plans to add support for oauth or other auth strategies?

I'm not very familiar with OpenAPI yet, but I noticed in the spec (http://spec.openapis.org/oas/v3.0.3) that each endpoint has an optional `security` section, and you can define security schemes to use throughout the API Schema. Would it be in scope for Dropshot to generate these sections?

**Comment by davepacheco** [comment]
Yeah, this is an important area.  For the projects where we intend to use Dropshot, we haven't yet gotten to the point of implementing authentication or authorization, so there's nothing there yet.  At the most basic level, I expect you can do whatever you might need by pulling headers out of the request and doing whatever custom processing you need for authentication and authorization.  I wrote some notes on how we expect to factor such code in #58:

> When we do get there, my intent is that we would create a pattern of utility functions that return typed values. For example, instead of adding an early authentication handler that fills in request.auth, you'd have an authentication function that returns an AuthzContext. Then, anything that needs that information consumes the AuthzContext. As an author of a handler, you know if you've got an AuthzContext available and, if not, how to get one (call the utility function). This composes, too: you can have an authorization function that returns an AuthnContext, and the utility function that returns one can consume the AuthzContext. Then anything that requires authorization can consume just the AuthnContext, and you know it's been authenticated and authorized (possibly with details in that structure).

As I said, this is vaporware right now.

I think you're also asking about implementations of specific authentication schemes.  We're intending to support client TLS certificates and I think HTTP signatures.  I'm not sure about oauth and other mechanisms.  My expectation is that these could just be different utility functions (or structs or traits or whatever) that consumers could use from their handlers, and they might not even need to come from Dropshot at all.  An open question for me is what interfaces can (and should) be shared between handlers.  Like, does it make sense to have an AuthContext trait, or is that necessarily specific to an application or the authentication mechanism?

**Comment by mikeyhew** [comment]
@davepacheco Thanks for getting back to me. I ended up doing something like this, which if I'm not mistaken is the pattern you described in that thread:

```rust
struct AuthContext {
    // contains info about user, client etc.
}

async fn do_auth(rctx: &Arc<RequestContext>) -> Result<AuthContext, HttpError> {
    // get the bearer token from request headers, return Ok(AuthContext) if it's valid, or an unauthorized error if not
}
```

and calling `do_auth` from within the endpoint handlers. It's turned out pretty well, actually. The only thing really missing is being able to set the security section, which I think (still need to look into it more to confirm) is what we need to set in order to be able to send authenticated requests in the swagger docs we generate - see the endpoints on https://petstore.swagger.io/#/ for an example.

By the way, what do you guys use to generate your documentation? Swagger-ui or something else?

**Comment by davepacheco** [comment]
Nice!  I'm glad to hear that went well.  @ahl, do you have thoughts on the "security" section bit?

As for docs: I think @ahl and maybe @plainspace had played around a bit, but we haven't spent much time with the docs yet.  It's on our list as a pretty important element, but we're still early in the stage of prototyping several APIs.

**Comment by plainspace** [comment]
@mikeyhew We have been experimenting with Swagger and Redoc. We've also done some prototyping with a custom implementation (which we like better than the other two) but we haven't made a decision yet.

**Comment by davepacheco** [comment]
I think the questions here are answered, at least given where things are now.  If not, please reopen!
