### ISSUE TITLE
Upgrade to tokio 0.3

### ISSUE THREAD

**Issue by mikeyhew** [oxidecomputer/dropshot#60]
Tokio 0.3 came out in mid-october (https://tokio.rs/blog/2020-10-tokio-0-3), and they're now on 0.3.3, so it seems like it should be stable enough to upgrade to now. I haven't done an upgrade from 0.2  - 0.3, but just speculating, it looks like the main thing to do is use the new feature flag names, and call the `.compat()` method from `tokio-compat-02` to wrap futures from crates that are still on 0.2.

**Comment by seanpianka** [comment]
Can you open a PR with the modified Cargo.toml? We can see what fails during compilation then.

**Comment by mikeyhew** [comment]
It looks like I'm a bit early, hyper [just updated to tokio 0.3](https://github.com/hyperium/hyper/pull/23190), but it won't be released until hyper 0.14 is out.

**Comment by davepacheco** [comment]
I think that link was supposed to be to [https://github.com/hyperium/hyper/issues/2319](2319).  I also found [2352](https://github.com/hyperium/hyper/issues/2352), in which the hyper authors explain that the plan will be to release 0.14 when tokio 1.0 is out.  Given that, I think the most sensible thing for us is to wait for both of those and then update Dropshot to the newer tokio and hyper.

**Comment by mikeyhew** [comment]
Thanks! I updated the link. That sounds reasonable, I don't know of any tokio 0.3 features that I'm dying to have, so it's not really worth upgrading until the hyper release comes out

**Comment by davepacheco** [comment]
It looks like tokio 1.0 and hyper 0.14 were released today.
