### ISSUE TITLE
openapi: deal with error return types

### ISSUE THREAD

**Issue by ahl** [oxidecomputer/dropshot#7]
We may do this in several PRs, but the end state should be that the various error types are well-captured for each endpoint. This will likely require us to think more carefully about the specific return types we want to expose to developers, the appropriate granularity, and the types of remediation we expect developers to take in the case of failures.

There are types of failures where we have more information:
- we could provide detailed information about input validation failures
- we could provide specific guidance about retries in the case of 503 (service unavailable)
- etc.

Ideally we should make use of the `components/responses` field of OpenAPI to minimize the number of times these shared error structures are represented in the OpenAPI document.

**Comment by WasabiFan** [comment]
Would it be correct to say that _currently_ there is no way to output errors in the `responses` section of an endpoint's OpenAPI doc? (Even manually, barring postprocessing of the JSON structure.) Currently, it looks like only [one possible response](https://github.com/oxidecomputer/dropshot/blob/1c6f4d156c670edc6476ca5bcdffc33a7001cbc7/dropshot/src/api_description.rs#L38) can be modeled in the registered routes.
